title: 新成
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://JunFuXu.github.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: 主页
   url: /index.html
 - title: 关于
   url: /about
 - title: Contact
   url: /contact
 - title: 简历
   url: /resume

social:
   github: JunFuXu
   twitter: JunFuXu
   facebook: JunFuXu
   email: xujunfu@shu.edu.cn
