title: 落叶飘香
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://luonaibin.github.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: 主页
   url: http://luonaibin.github.io/index.html
   target: _self
 - title: GitHub
   url: https://github.com/luonaibin
   target: _blank
 - title: 简历
   url: http://luonaibin.github.io/resume
   target: _blank
 - title: 关于
   url: http://luonaibin.github.io/about
   target: _self

social:
   github: luonaibin
   twitter: luonaibin
   facebook: luonaibin
   email: jsluonaibin@163.cn
